python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 0 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 10 >| testing_results/resnet50_epoch10.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 0 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 5 >| testing_results/resnet50_epoch5.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 0 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 4 >| testing_results/resnet50_epoch4.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 0 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 3 >| testing_results/resnet50_epoch3.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 0 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 2 >| testing_results/resnet50_epoch2.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 0 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 1 >| testing_results/resnet50_epoch1.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 1 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 10 >| testing_results/vit_epoch10.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 1 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 5 >| testing_results/vit_epoch5.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 1 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 4 >| testing_results/vit_epoch4.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 1 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 3 >| testing_results/vit_epoch3.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 1 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 2 >| testing_results/vit_epoch2.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch 1 --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 1 >| testing_results/vit_epoch1.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch DARTS --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 10 >| testing_results/darts_epoch10.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch DARTS --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 5 >| testing_results/darts_epoch5.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch DARTS --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 4 >| testing_results/darts_epoch4.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch DARTS --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 3 >| testing_results/darts_epoch3.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch DARTS --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 2 >| testing_results/darts_epoch2.txt 2>&1
python experiments/sgd/detector/test_detector.py -d PennFudanPed --arch DARTS --ckpt ./checkpoints/ghn2_imagenet.pt --init_channels 48 --layers 14 --epochs 1 >| testing_results/darts_epoch1.txt 2>&1
